include:
  - path: settings.json
  - path: gitignore
    destination: .gitignore
  - path: profiles.json
    destination: folder/
exclude:
  - .gitignore # is the same as 'path: .gitignore'

windows:
  destination: '%appdata%/Code/User'
linux:
  destination: ~/.config/Code/User
macos:
  destination: ~/Library/Application Support/Code/User/settings.json
